config/routes.rb
Rails.application.routes.draw do
  root :to => 'tasks#index'
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :details
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for task do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit "Save", class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit the task </h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>All tasks</h1>

<% @tasks.each do |task| %>
<input type="checkbox" id="task" name="task" value="title">
<p><%= link_to task.title, details_path(task) %></p>
<% end %>

<%= link_to 'Add a new task', tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create Task</h1>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p>Details: <%= @task.details%> </p>

<%= link_to "Go back to tasks", tasks_path %>
<%= link_to "Edit", edit_task_path(@task) %>
<%= link_to "Delete", delete_task_path(@task), method: :delete, data: {confirm: "Are you sure?"} %>